### PR TITLE
YELLOW-5847

### PR DESCRIPTION
**Pull request by ashkanF**
Adds support for BankID v6.
The interface description is [here](https://www.bankid.com/utvecklare/guider/teknisk-integrationsguide/graenssnittsbeskrivning)!

### CODE REVIEW

**Review by sebwih — APPROVED** [review]
What is the plan going forward with this repo? Should we keep our own lib? Continue with the opensource version and contribute to updating upstream?

**Review by micke136 — APPROVED** [review]
👍

**Comment by ashkanF** [comment]
> What is the plan going forward with this repo? Should we keep our own lib? Continue with the opensource version and contribute to updating upstream?

Well, we are going to keep this fork as a temporary solution until we get the chance to develop our own lib. 
And from what I understood, we are not going to contribute to the upstream repo. :)

**Review by egoon — APPROVED** [review]

**Comment by egoon** [comment]
> Well, we are going to keep this fork as a temporary solution until we get the chance to develop our own lib. And from what I understood, we are not going to contribute to the upstream repo. :)

'Temporary', as in 'we'll only use it for a decade or so'? 😉

**Pull request merged**
